name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  workflows:
    permissions:
      pull-requests: read
    uses: finleyfamily/workflows/.github/workflows/hass-repository.ci.yml@master
