name: Repository Updater

# yamllint disable-line rule:truthy
on:
  repository_dispatch:
    types:
      - update

jobs:
  auth:
    name: Create app token
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.app-token.outputs.token }}
    steps:
      - name: 🏗 Create app token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.FINLEY_APP_ID }}
          private-key: ${{ secrets.FINLEY_APP_PRIVATE_KEY }}
  workflows:
    needs: auth
    uses: finleyfamily/workflows/.github/workflows/hass-repository.updater.yml@master
    secrets:
      UPDATER_TOKEN: ${{ needs.auth.outputs.token }}
