name: Repository Updater

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/repository-updater.yml
  repository_dispatch:
    types: ["update"]

jobs:
  workflows:
    uses: finleyfamily/workflows/.github/workflows/hass-repository.updater.yml@master
    secrets:
      UPDATER_TOKEN: ${{ secrets.HASS_UPDATER_TOKEN }}
