name: Repository Updater

# yamllint disable-line rule:truthy
on:
  repository_dispatch:
    types:
      - update

jobs:
  workflows:
    uses: finleyfamily/workflows/.github/workflows/hass-repository.updater.yml@master
    secrets:
      app-private-key: ${{ secrets.FINLEY_APP_PRIVATE_KEY }}
